# Config file for automatic testing at travis-ci.org

sudo: false
language: python

matrix:
    include:
      - python: 2.7
        env: TOXENV=py27
      - python: 3.3
        env: TOXENV=py33
      - python: 3.4
        env: TOXENV=py34
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: pypy
        env: TOXENV=pypy
      - python: 3.5
        env: TOXENV=flake8

script: tox

install:
    - pip install tox


after_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - pip install codecov
    - codecov -e TOXENV TRAVIS_OS_NAME
