# Config file for automatic testing at travis-ci.org

sudo: false
language: python

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "nightly"

env:
    - TOX_ENV=py27
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=py35
    - TOX_ENV=pypy
    - TOX_ENV=flake8

script: tox -e $TOX_ENV

install:
    - pip install tox

after_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - pip install codecov
    - codecov -e TOX_ENV TRAVIS_OS_NAME
