# Config file for automatic testing at travis-ci.org
dist: xenial
sudo: false
language: python

matrix:
    include:
      - python: 3.7
        env: TOXENV=lint
      - python: 2.7
        env: TOXENV=py27
      - python: 3.5
        env: TOXENV=py35
      - python: 3.6
        env: TOXENV=py36
      - python: 3.7
        env: TOXENV=py37
      - python: 3.8-dev
        env: TOXENV=py38
      - python: pypy
        env: TOXENV=pypy

script: tox

install:
    - pip install tox


after_success:
    # Report coverage results to codecov.io
    # and export tox environment variables
    - pip install codecov
    - codecov -e TOXENV TRAVIS_OS_NAME
